annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump mariadb to 1.0.4
    - kind: changed
      description: Change tag to version-v2.0.1 to reduce the number of chart updates.
  artifacthub.io/images: |
    - name: papermerge
      image: ghcr.io/linuxserver/papermerge:version-v2.0.1
apiVersion: v2
appVersion: v2.0.1
dependencies:
- name: common
  repository: https://nicholaswilde.github.io/helm-charts/
  version: ~0.1.13
- condition: mariadb.enabled
  name: mariadb
  repository: https://nicholaswilde.github.io/helm-charts/
  version: ~1.0.4
- condition: postgres.enabled
  name: postgres
  repository: https://nicholaswilde.github.io/helm-charts/
  version: ~0.1.0
description: Designed for scanned documents. Perfect software that will help you reduce
  paper clutter and keep your business organized.
home: https://github.com/nicholaswilde/helm-charts/tree/main/charts/papermerge
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/papermerge-icon.png
keywords:
- paper
- merge
- document
- scan
- scanner
maintainers:
- email: ncwilde43@gmail.com
  name: nicholaswilde
name: papermerge
sources:
- https://www.papermerge.com/
- https://hub.docker.com/r/linuxserver/papermerge
type: application
version: 1.0.2
